PACKAGE_NAME_MAP = {
        "DEHRADUN"           : "AU-DDN",
        "AGRA"               : "AU-AGR",
        "DELHI"              : "AU-NWD",
        "CHANDIGARH"         : "AU-CHA",
        "ROHTAK"            : "AU-RTK",    
        "NAINITAL"           : "AU-NAI",
        "LUCKNOW"            : "AU-LKO",
        "PRAYAGRAJ"          : "AU-ALD",
        "JHANSI"             : "AU-JHA",
        "VARANASI"           : "AU-VNS",
        "JALANDHAR"          : "AU-JAL",
        "DHARAMSHALA"        : "AU-DSL",
        "ALIGARH"            : "AU-ALG",
        "GORAKHPUR"          : "AU-GKP",
        "BAREILLY"           : "AU-BLY",
        "MEERUT"             : "AU-MRT",
        "MORADABAD"          : "AU-MBD",
        "KANPUR"             : "AU-KNP",
        "SHIMLA"             : "AU-SML",
        "HISAR"              : "AU-HIS",
        "KARNAL"             : "AU-KNL",
        "JAMMU"              : "AU-JMU",
    }

# CATEGORY_TO_SUBCAT = {
#     "Display": "GO8",
#     "Tender": "GO5",
#     "Public Notices": "GO8",
#     "Auction": "GO5",
#     "Recruitment": "GO8",
#     "Others": "GO8",
#     "Admission Notice": "GO8",
#     "Announcements": "GO8",
# }